### PR TITLE
Add scholarship info

### PR DESCRIPTION
**Pull request by ajdapretnar**
Added info on scholarship options.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@astaric I know you are super busy, but perhaps you need some time off to deal with the wonderful css. 😁 I have no idea how to properly set text to be at 8 col and button to 2 col. Whatever I do, they are always at 50:50.

Also a comment on how presentable this looks would be great. 🌹

**Comment by astaric** [comment]
In chrome, they are positioned like this:

screen shot 2017-05-27 at 08 27 07

If you show me (image/sketch/sth else) how you wanted it to look like, I can help you fix the css. 

IMHO, the button on the right seems off, as the one above is centered. and this one is right aligned. I would consider replacing the button with a link (<a href=#>Submit your motivational letter here</a> or similar) following the text (or somewhere else) to avoid having two similar looking but different buttons this close.

**Comment by ajdapretnar** [comment]
> I would consider replacing the button with a link (Submit your motivational letter here or similar) following the text (or somewhere else) to avoid having two similar looking but different buttons this close.

Gottcha. I just hope it's visible enough. :) I can fix that myself. 👍

**Comment by ajdapretnar** [comment]
Done. I will merge so I can send the link to targeted departments.

**Pull request merged**
