### PR TITLE
New template for screenshots.

### PR DESCRIPTION
**Pull request by PrimozGodec**
Sorry because I am late. I haven't have enough time on my way and also internet connection was bad.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@astaric Would you care to check as well?

**Comment by astaric** [comment]
Could you rebase the code instead of merging it? Last time the manual merge commit ruined the css files and it took me quite some time to figure out what was going on.

**Comment by ajdapretnar** [comment]
I get no conflicts. Do you? 😮

**Comment by astaric** [comment]
I am complaining that the PR contains merge commits when it should only contain the changes.

**Comment by ajdapretnar** [comment]
Yeses, we need only commit f1c818b.

**Comment by PrimozGodec** [comment]
Sorry for that. Now I rebased.

**Pull request merged**
