### PR TITLE
[ENH] Add training pages

### PR DESCRIPTION
**Pull request by jasminka**
Added  pages for Orange training. TODO:

- [ ] Get in touch redirect
- [ ] Auto scroll to course title after clicking the course link

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I just added a 'Work In Progress' tag, so it is clear this needs some editing before merging. :)

**Comment by ajdapretnar** [comment]
Should I write text for all slots? So you have something to fill the pages with?

**Comment by astaric** [comment]
If you are going to write the texts, I suggest you edit the files modified in this branch and push additional commits to jasmina's branch. This way, we keep everything in a single place.

**Comment by ajdapretnar** [comment]
Yessir!

**Comment by ajdapretnar** [comment]
I have added some drafts for texts, just so we can better imagine what this site is about.

**Comment by ajdapretnar** [comment]
@BlazZupan There's a lot of unnecessary commits you've just pushed. Could you please check and clean?

**Pull request merged**
